services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  bot:
    build: .
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis-data: